SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

ASTEROID_MIN_RADIUS = 40
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

PLAYER_RADIUS = 12
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 150
PLAYER_ACCELERATION = PLAYER_SPEED * 2 

SHOT_RADIUS = 5 
PLAYER_SHOOT_SPEED = 500 
PLAYER_SHOOT_COOLDOWN = 0.3

LASER_SHOT_SPEED = 750 
LASER_SHOT_COOLDOWN = 0.6 

